
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibds-model-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ibds
  template:
    metadata:
      labels:
        app: ibds
    spec:
      containers:
        - name: ibds-server
          image: yourrepo/ibds:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: ibds-service
spec:
  selector:
    app: ibds
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
